### ISSUE TITLE
Two maps on same page

### ISSUE THREAD

**Issue by glomium** [divio/djangocms-googlemap#12]
Hi,

I have problems displaying two Maps on the same page. The DOM is properly rendered for each plugin, but the googlemaps API breaks with the error-message:

```
k[Jc].maps.Load is not a function
```

Probably because the API is loaded twice. Undoing the changes from PR #5 solves the issue.

Sebastian

**Comment by creimers** [comment]
+ 1

**Comment by eandersons** [comment]
I encoutered the same problem.
Versions:

    Django: 1.7.7
    Django CMS: 3.0.12
    djangocms-googlemap: 0.2

To solve the problem, I copied the template `templates/cms/plugins/googlemap.html` and changed this (about 68th line)

    {% addtoblock "js" %}
    <script type="text/javascript" src="https://maps-api-ssl.google.com/maps/api/js?v=3&amp;sensor=true&amp;callback=initializeMap{{ object.pk }}"></script>
    {% endaddtoblock %}

to this

    {%addtoblock "js"%}
      <script type="text/javascript" src="https://maps-api-ssl.google.com/maps/api/js?v=3&amp;sensor=true">
      </script>

      <script type="text/javascript">
        $(function() {
          initializeMap{{object.pk}}();
        });
      </script>
    {%endaddtoblock%}

It would be nice if this was supported out of the box.

**Comment by creimers** [comment]
It works with version ``0.0.5``. I'm using that for now.

**Comment by ygwain** [comment]
I have the same

**Comment by selectnull** [comment]
I have created PR that solves this issue. For those having the same issue, until it's merged, you can just copy googlemap.html template from my repo and copy it to your templates directory (for example, `templates/cms/plugins/googlemap.html`)

**Comment by FinalAngel** [comment]
Fixed in the latest version https://github.com/divio/djangocms-googlemap/pull/46
